---
title: "Model Fitting and Evaluation"
author: "Frank Ockerman"
date: "`r Sys.Date()`"
output: pdf_document
---


```{r, setup}
if(!require(pacman)){install.packages(pacman)}
p_load(data.table,
       ggplot2,
       magrittr,
       parallel,
       doMC,
       pROC,
       glmnet)
ncores <- max(detectCores() - 2, 1)
```

```{r, load data}
load("./data/answers_topics.RData")
load("./data/features.RData")
load("./data/topics.RData")
load("./data/sentiment.RData")
features <- data.table(features)
topics <- data.table(topics)
dt_sent <- data.table(dt_sent)
```

```{r, merge features}
# mean impute missing values
topics <- topics[, lapply(.SD, function(topic) {
  topic[is.na(topic)] <- mean(topic, na.rm = T)
  return(topic)
})]

# sort data tables
setorder(topics, doc_id); setorder(features, answer_id); setorder(dt_sent, id)

# merge data tables
DT = cbind(features[, .SD, .SDcols = (1:34)[-c(1:3)]],
           topics[, .SD, .SDcols = (1:12)[-c(1:2)]],
           dt_sent[, -"id"]
           )

# rename topic features
DT$elapsed_time <- as.numeric(DT$elapsed_time)
names(DT)[names(DT) %in% as.character(1:8)] <- paste0("topic_", names(DT)[names(DT) %in% as.character(1:8)])
```

```{r, model data}
# covariate matrix
x <- DT[, -c(1:2)] %>% as.matrix()

# test/train split
set.seed(11351235)
train_id <- sample(1:nrow(DT), size = nrow(DT) * 0.7)
x.train <- x[train_id,]
x.test <- x[-train_id,]
y.acc <- DT[, IsAcceptedAnswer] %>% as.matrix()
y.acc.train <- y.acc[train_id]
y.acc.test <- y.acc[-train_id]
y.score <- DT[, answer_score]
y.score[y.score > 30] <- 30 # truncate scores
#y.score <- (y.score - mean(y.score)) / sd(y.score) # normalize
y.score.train <- y.score[train_id]
y.score.test <- y.score[-train_id]
```

```{r, acceptance model}
# uncomment below to run binomial lasso for acceptance
#set.seed(1234213)
#doMC::registerDoMC(ncores)
#mod.acc.cv <- cv.glmnet(x = x.train, y = y.acc.train, folds = 10, trace.it = T,
#                        family = binomial,alpha = 1, parallel = T)
#save(mod.acc.cv, file = "data/mod.acc.cv.RData")
load("data/mod.acc.cv.RData")
```

```{r, acceptance auc and ROC}
pred.acc <- predict(mod.acc.cv, newx = x.test, s = "lambda.min")
pred.acc <- exp(pred.acc) / (1 + exp(pred.acc)) %>% as.vector()
y.acc.test %<>% as.vector()
df.acc <- data.table(pred.acc, y.acc.test)
setnames(df.acc, c("pred", "resp"))
rocplot <- ggplot(df.acc, aes(m = pred, d = resp))+ geom_roc(n.cuts=20,labels=FALSE)
png("../roc.png")
rocplot + style_roc(theme = theme_grey) + geom_rocci()
dev.off()
auc(predictor = pred.acc, response = y.acc.test)
```

```{r, score}
# uncomment below to run guassian lasso for score
#set.seed(1347091)
#doMC::registerDoMC(ncores)
#mod.score.cv <- cv.glmnet(x = x.train, y = y.score.train, folds = 10, trace.it = T,
#                        family = gaussian, alpha = 1, parallel = T)
#save(mod.score.cv, file = "data/mod.score.cv.RData")
load("data/mod.score.cv.RData")
```

```{r, score resid vs fitted}
pred.score <- predict(mod.score.cv, newx = x.test, newy = y.score.test, s = "lambda.min")
df.score <- data.table(pred.score, y.score.test)
setnames(df.score, c("pred", "resp"))
png("../score_resid.png")
df.score %>% ggplot(aes(x = pred, y = resp - pred)) + geom_point() + xlab("Predicted Score") + ylab("Residual")
dev.off()
```

```{r, mae and r^2}
mean(abs(df.score[, pred - resp])) # mae
mod.score.cv$glmnet.fit$dev.ratio[which.min(mod.score.cv$cvm)] #r^2
```
